#!/bin/sh

Adam=Away
Valeria=Away
Guest=Away

macadresser=`wl -i eth1 assoclist`
antal=0
antal=`qcsapi_sockrpc get_count_assoc wifi0`

while [ $antal -gt 0 ]
do
  antal=`expr $antal - 1`
  macadresser="`qcsapi_sockrpc get_station_mac_addr wifi0 $antal`;$macadresser"
done

case "$macadresser" in
 *XX:XX:XX:XX:XX:XX*)
 Adam=Home
 ;;
esac

case "$macadresser" in
 *XX:XX:XX:XX:XX:XX*)
 Valeria=Home
 ;;
esac

case "$macadresser" in
 *XX:XX:XX:XX:XX:XX*)
 Guest=Home
 ;;
esac

if [ "$Adam" = Home ]
then
 if [ ! -f /jffs/scripts/CheckUser/AdamHome ]
 then
  touch /jffs/scripts/CheckUser/AdamHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/home?access_token=<Access Token>" -k
 fi
else
 if [ -f /jffs/scripts/CheckUser/AdamHome ]
 then
  rm -f /jffs/scripts/CheckUser/AdamHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/away?access_token=<Access Token>" -k
  fi
fi

if [ "$Valeria" = Home ]
then
 if [ ! -f /jffs/scripts/CheckUser/ValeriaHome ]
 then
  touch /jffs/scripts/CheckUser/ValeriaHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/home?access_token=<Access Token>" -k
 fi
else
 if [ -f /jffs/scripts/CheckUser/ValeriaHome ]
 then
  rm -f /jffs/scripts/CheckUser/ValeriaHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/away?access_token=<Access Token>" -k
 fi
fi

if [ "$Guest" = Home ]
then
 if [ ! -f /jffs/scripts/CheckUser/GuestHome ]
 then
  touch /jffs/scripts/CheckUser/GuestHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/home?access_token=<Access Token>" -k
 fi
else
 if [ -f /jffs/scripts/CheckUser/GuestHome ]
 then
  rm -f /jffs/scripts/CheckUser/GuestHome
  curl "https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/installations/<AppID>/Phone/away?access_token=<Access Token>" -k
 fi
fi
